@startuml

'Nå vet vi ikke helt hvordan dette skal fungere da
'Kan tynne ned om det blir for mye ting, men er kult

actor user
entity SEAT
database db


user --> SEAT: Spesifiserer at en allerede har en bruker
user <-- SEAT: Skriv brukernavn (Arrangor navn)
user --> SEAT: Brukernavn (nvanrognarrA)
SEAT --> db: Finnes denne brukeren?
SEAT <-- db: Ja
user <-- SEAT: Skriv passord
user --> SEAT: Passord (drossap)
SEAT --> db: Stemmer dette passordet?
SEAT <-- db: Ja
user <-- SEAT: Du er logget inn.

@enduml