@startuml

actor user
entity SEAT
control Database.java as data
database db


user --> SEAT: Spesifiserer at en trenger en ny bruker
user <-- SEAT: Skriv inn onsket brukernavn / Arrangor navn
user --> SEAT: UserSoft™

' Her er evt passord om det skal bli en ting.
SEAT --> SEAT: organizer = new Organizer(usersoft)
SEAT --> data: addOrganizer(organizer)
data --> db: INSERT INTO arrangor organizer
user <-- SEAT: Din bruker er naa laget, du kan logge inn


@enduml