@startuml


user --> SEAT:
user <-- SEAT:
user --> SEAT:
user <-- SEAT:
user --> SEAT:
user <-- SEAT:
user --> SEAT:
user <-- SEAT:
user --> SEAT:
user <-- SEAT:
user --> SEAT:
user <-- SEAT:
user --> SEAT:
user <-- SEAT:
user --> SEAT:
@enduml