@startuml

actor user
entity OrganizerConsole.java as SEAT
control Database.java as data
database db

user --> SEAT: Nytt Arrangement! \n organizerCreatesArrangement()
note left
	Går ut ifra at bruker allerede
	er logget inn i arrangor konto
end note
SEAT --> SEAT: Arrangement newArrangement\n = createArrangementPrompt()
user <-- SEAT: Skriv inn ønsket tittel
user --> SEAT: UserParty
user <-- SEAT: Skriv inn ønsket \n arrangement beskrivelse
user --> SEAT: Bring * from friends
user <-- SEAT: Skriv inn arrangementets dato
user --> SEAT: day-month-year
user <-- SEAT: Skriv inn hvor mange billetter \n som skal selges
user --> SEAT: 200
SEAT <-- SEAT: new Arrangement(aboveValues)
SEAT --> data: createEvent(aboveArrangement)
data --> db: INSERT INTO arrangement aboveArrangement

@enduml