@startuml

actor user
entity SEAT
database db

user --> SEAT:
SEAT --> db: displayEvents()
SEAT <-- db: returns ResultSet med arrangementer
SEAT --> SEAT: for ResultSet{ new Arrangement(info) }
user <-- SEAT: Presenterer bruker med valg
user --> SEAT: Velger onsket arrangement
SEAT --> SEAT: Starter (011)

@enduml